# Global config
name = "cfgx"

# Simple types: string, int, float, bool
[server]
addr = ":8080"
timeout = "30s"
read_timeout = "15s"
write_timeout = "15s"
idle_timeout = "5m"
max_header_bytes = 1048576
debug = true

# Nested structures (multiple levels)
[database]
dsn = "postgres://localhost/myapp"
max_open_conns = 25
max_idle_conns = 5
conn_max_lifetime = "5m"

[database.pool]
enabled = true
min_size = 2
max_size = 10

# Arrays of primitives
[cache]
enabled = true
ttl = "1h"
max_entries = 10000
outputs = ["stdout", "file"]

[cache.redis]
addr = "localhost:6379"
password = ""
db = 0

# String, int, and float arrays
[service]
name = "api"
allowed_origins = ["https://example.com", "https://app.example.com"]
ports = [8080, 8081, 8082]
weights = [1.0, 2.5, 3.7]
features = ["auth", "cache", "metrics"]

# Deep nesting
[app]
name = "myservice"
version = "1.0.0"

[app.logging]
level = "info"
file = "/var/log/app.log"
format = "json"

[app.logging.rotation]
max_size = 100
max_age = 30
compress = true

# Array of tables (TOML [[section]])
[[endpoints]]
path = "/api/v1"
methods = ["GET", "POST"]
rate_limit = 100

[[endpoints]]
path = "/api/v2"
methods = ["GET", "POST", "PUT", "DELETE"]
rate_limit = 200

[[features]]
name = "authentication"
enabled = true
priority = 1

[[features]]
name = "rate_limiting"
enabled = true
priority = 2

[[features]]
name = "caching"
enabled = false
priority = 3
