// Code generated by cfgx. DO NOT EDIT.

package config

type DatabaseConfig struct {
	Dsn          string
	MaxIdleConns int64
	MaxOpenConns int64
}

type FeaturesItem struct {
	Enabled  bool
	Name     string
	Priority int64
}

type LoggingConfig struct {
	Format  string
	Level   string
	Outputs []string
}

type RedisConfig struct {
	Addr     string
	Db       int64
	Password string
}

type ServerConfig struct {
	Addr         string
	ReadTimeout  int64
	WriteTimeout int64
}

var Database = DatabaseConfig{
	Dsn:          "postgres://localhost:5432/myapp",
	MaxIdleConns: 5,
	MaxOpenConns: 25,
}

var Features = []FeaturesItem{
	FeaturesItem{
		Enabled:  true,
		Name:     "authentication",
		Priority: 1,
	},
}

var Logging = LoggingConfig{
	Format:  "json",
	Level:   "info",
	Outputs: []string{"stdout"},
}

var Redis = RedisConfig{
	Addr:     "localhost:6379",
	Db:       0,
	Password: "",
}

var Server = ServerConfig{
	Addr:         ":8080",
	ReadTimeout:  15,
	WriteTimeout: 15,
}
