// Code generated by cfgx. DO NOT EDIT.

package getter_config

import (
	"os"
	"strconv"
	"time"
)

type appConfig struct{}

type apploggingConfig struct{}

type apploggingrotationConfig struct{}

type cacheConfig struct{}

type cacheredisConfig struct{}

type databaseConfig struct{}

type databasepoolConfig struct{}

type endpointsItem struct{}

type featuresItem struct{}

type serverConfig struct{}

type serviceConfig struct{}

func (appConfig) Logging() apploggingConfig {
	return apploggingConfig{}
}

func (apploggingConfig) File() string {
	if v := os.Getenv("CONFIG_APP_LOGGING_FILE"); v != "" {
		return v
	}
	return "/var/log/app.log"
}

func (apploggingConfig) Format() string {
	if v := os.Getenv("CONFIG_APP_LOGGING_FORMAT"); v != "" {
		return v
	}
	return "json"
}

func (apploggingConfig) Level() string {
	if v := os.Getenv("CONFIG_APP_LOGGING_LEVEL"); v != "" {
		return v
	}
	return "info"
}

func (apploggingConfig) Rotation() apploggingrotationConfig {
	return apploggingrotationConfig{}
}

func (apploggingrotationConfig) Compress() bool {
	if v := os.Getenv("CONFIG_APP_LOGGING_ROTATION_COMPRESS"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			return b
		}
	}
	return true
}

func (apploggingrotationConfig) MaxAge() int64 {
	if v := os.Getenv("CONFIG_APP_LOGGING_ROTATION_MAX_AGE"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 30
}

func (apploggingrotationConfig) MaxSize() int64 {
	if v := os.Getenv("CONFIG_APP_LOGGING_ROTATION_MAX_SIZE"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 100
}

func (appConfig) Name() string {
	if v := os.Getenv("CONFIG_APP_NAME"); v != "" {
		return v
	}
	return "myservice"
}

func (appConfig) Version() string {
	if v := os.Getenv("CONFIG_APP_VERSION"); v != "" {
		return v
	}
	return "1.0.0"
}

func (cacheConfig) Enabled() bool {
	if v := os.Getenv("CONFIG_CACHE_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			return b
		}
	}
	return true
}

func (cacheConfig) MaxEntries() int64 {
	if v := os.Getenv("CONFIG_CACHE_MAX_ENTRIES"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 10000
}

func (cacheConfig) Outputs() []string {
	if v := os.Getenv("CONFIG_CACHE_OUTPUTS"); v != "" {
		// Array overrides not supported via env vars
	}
	return []string{"stdout", "file"}
}

func (cacheConfig) Redis() cacheredisConfig {
	return cacheredisConfig{}
}

func (cacheredisConfig) Addr() string {
	if v := os.Getenv("CONFIG_CACHE_REDIS_ADDR"); v != "" {
		return v
	}
	return "localhost:6379"
}

func (cacheredisConfig) Db() int64 {
	if v := os.Getenv("CONFIG_CACHE_REDIS_DB"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 0
}

func (cacheredisConfig) Password() string {
	if v := os.Getenv("CONFIG_CACHE_REDIS_PASSWORD"); v != "" {
		return v
	}
	return ""
}

func (cacheConfig) Ttl() time.Duration {
	if v := os.Getenv("CONFIG_CACHE_TTL"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 1 * time.Hour
}

func (databaseConfig) ConnMaxLifetime() time.Duration {
	if v := os.Getenv("CONFIG_DATABASE_CONN_MAX_LIFETIME"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 5 * time.Minute
}

func (databaseConfig) Dsn() string {
	if v := os.Getenv("CONFIG_DATABASE_DSN"); v != "" {
		return v
	}
	return "postgres://localhost/myapp"
}

func (databaseConfig) MaxIdleConns() int64 {
	if v := os.Getenv("CONFIG_DATABASE_MAX_IDLE_CONNS"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 5
}

func (databaseConfig) MaxOpenConns() int64 {
	if v := os.Getenv("CONFIG_DATABASE_MAX_OPEN_CONNS"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 25
}

func (databaseConfig) Pool() databasepoolConfig {
	return databasepoolConfig{}
}

func (databasepoolConfig) Enabled() bool {
	if v := os.Getenv("CONFIG_DATABASE_POOL_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			return b
		}
	}
	return true
}

func (databasepoolConfig) MaxSize() int64 {
	if v := os.Getenv("CONFIG_DATABASE_POOL_MAX_SIZE"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 10
}

func (databasepoolConfig) MinSize() int64 {
	if v := os.Getenv("CONFIG_DATABASE_POOL_MIN_SIZE"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 2
}

func (endpointsItem) Methods() []string {
	if v := os.Getenv("CONFIG_ENDPOINTS_METHODS"); v != "" {
		// Array overrides not supported via env vars
	}
	return []string{"GET", "POST"}
}

func (endpointsItem) Path() string {
	if v := os.Getenv("CONFIG_ENDPOINTS_PATH"); v != "" {
		return v
	}
	return "/api/v1"
}

func (endpointsItem) RateLimit() int64 {
	if v := os.Getenv("CONFIG_ENDPOINTS_RATE_LIMIT"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 100
}

func (featuresItem) Enabled() bool {
	if v := os.Getenv("CONFIG_FEATURES_ENABLED"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			return b
		}
	}
	return true
}

func (featuresItem) Name() string {
	if v := os.Getenv("CONFIG_FEATURES_NAME"); v != "" {
		return v
	}
	return "authentication"
}

func (featuresItem) Priority() int64 {
	if v := os.Getenv("CONFIG_FEATURES_PRIORITY"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 1
}

func (serverConfig) Addr() string {
	if v := os.Getenv("CONFIG_SERVER_ADDR"); v != "" {
		return v
	}
	return ":8080"
}

func (serverConfig) Cert() []byte {
	// Check for file path to load
	if path := os.Getenv("CONFIG_SERVER_CERT"); path != "" {
		if data, err := os.ReadFile(path); err == nil {
			return data
		}
	}
	return []byte{
		0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x20, 0x43,
		0x45, 0x52, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x45, 0x2d, 0x2d,
		0x2d, 0x2d, 0x2d, 0x0a, 0x4d, 0x49, 0x49, 0x44, 0x58, 0x54, 0x43, 0x43,
		0x41, 0x6b, 0x57, 0x67, 0x41, 0x77, 0x49, 0x42, 0x41, 0x67, 0x49, 0x4a,
		0x41, 0x4b, 0x4c, 0x30, 0x55, 0x47, 0x2b, 0x6d, 0x52, 0x4b, 0x53, 0x7a,
		0x4d, 0x41, 0x30, 0x47, 0x43, 0x53, 0x71, 0x47, 0x53, 0x49, 0x62, 0x33,
		0x44, 0x51, 0x45, 0x42, 0x43, 0x77, 0x55, 0x41, 0x4d, 0x45, 0x55, 0x78,
		0x43, 0x7a, 0x41, 0x4a, 0x42, 0x67, 0x4e, 0x56, 0x0a, 0x42, 0x41, 0x59,
		0x54, 0x41, 0x6b, 0x46, 0x56, 0x4d, 0x52, 0x4d, 0x77, 0x45, 0x51, 0x59,
		0x44, 0x56, 0x51, 0x51, 0x49, 0x44, 0x41, 0x70, 0x54, 0x62, 0x32, 0x31,
		0x6c, 0x4c, 0x56, 0x4e, 0x30, 0x59, 0x58, 0x52, 0x6c, 0x4d, 0x53, 0x45,
		0x77, 0x48, 0x77, 0x59, 0x44, 0x56, 0x51, 0x51, 0x4b, 0x44, 0x42, 0x68,
		0x4a, 0x62, 0x6e, 0x52, 0x6c, 0x63, 0x6d, 0x35, 0x6c, 0x64, 0x43, 0x42,
		0x58, 0x0a, 0x61, 0x57, 0x52, 0x6e, 0x61, 0x58, 0x52, 0x7a, 0x49, 0x46,
		0x42, 0x30, 0x65, 0x53, 0x42, 0x4d, 0x64, 0x47, 0x51, 0x77, 0x48, 0x68,
		0x63, 0x4e, 0x4d, 0x54, 0x63, 0x77, 0x4f, 0x44, 0x49, 0x7a, 0x4d, 0x54,
		0x55, 0x78, 0x4e, 0x54, 0x45, 0x79, 0x57, 0x68, 0x63, 0x4e, 0x4d, 0x6a,
		0x63, 0x77, 0x4f, 0x44, 0x49, 0x78, 0x4d, 0x54, 0x55, 0x78, 0x4e, 0x54,
		0x45, 0x79, 0x57, 0x6a, 0x42, 0x46, 0x0a, 0x4d, 0x51, 0x73, 0x77, 0x43,
		0x51, 0x59, 0x44, 0x56, 0x51, 0x51, 0x47, 0x45, 0x77, 0x4a, 0x42, 0x56,
		0x54, 0x45, 0x54, 0x4d, 0x42, 0x45, 0x47, 0x41, 0x31, 0x55, 0x45, 0x43,
		0x41, 0x77, 0x4b, 0x55, 0x32, 0x39, 0x74, 0x5a, 0x53, 0x31, 0x54, 0x64,
		0x47, 0x46, 0x30, 0x5a, 0x54, 0x45, 0x68, 0x4d, 0x42, 0x38, 0x47, 0x41,
		0x31, 0x55, 0x45, 0x43, 0x67, 0x77, 0x59, 0x53, 0x57, 0x35, 0x30, 0x0a,
		0x5a, 0x58, 0x4a, 0x75, 0x5a, 0x58, 0x51, 0x67, 0x56, 0x32, 0x6c, 0x6b,
		0x5a, 0x32, 0x6c, 0x30, 0x63, 0x79, 0x42, 0x51, 0x64, 0x48, 0x6b, 0x67,
		0x54, 0x48, 0x52, 0x6b, 0x4d, 0x49, 0x49, 0x42, 0x49, 0x6a, 0x41, 0x4e,
		0x42, 0x67, 0x6b, 0x71, 0x68, 0x6b, 0x69, 0x47, 0x39, 0x77, 0x30, 0x42,
		0x41, 0x51, 0x45, 0x46, 0x41, 0x41, 0x4f, 0x43, 0x41, 0x51, 0x38, 0x41,
		0x4d, 0x49, 0x49, 0x42, 0x0a, 0x43, 0x67, 0x4b, 0x43, 0x41, 0x51, 0x45,
		0x41, 0x7a, 0x50, 0x4a, 0x6e, 0x36, 0x4e, 0x43, 0x4d, 0x6d, 0x4e, 0x47,
		0x70, 0x52, 0x68, 0x5a, 0x4b, 0x57, 0x58, 0x41, 0x36, 0x64, 0x47, 0x7a,
		0x70, 0x46, 0x33, 0x42, 0x4f, 0x38, 0x63, 0x47, 0x31, 0x59, 0x54, 0x2f,
		0x63, 0x53, 0x4c, 0x55, 0x4a, 0x75, 0x50, 0x4b, 0x69, 0x56, 0x6d, 0x48,
		0x59, 0x78, 0x59, 0x51, 0x7a, 0x38, 0x78, 0x51, 0x57, 0x0a, 0x2d, 0x2d,
		0x2d, 0x2d, 0x2d, 0x45, 0x4e, 0x44, 0x20, 0x43, 0x45, 0x52, 0x54, 0x49,
		0x46, 0x49, 0x43, 0x41, 0x54, 0x45, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x0a,
	}
}

func (serverConfig) Debug() bool {
	if v := os.Getenv("CONFIG_SERVER_DEBUG"); v != "" {
		if b, err := strconv.ParseBool(v); err == nil {
			return b
		}
	}
	return true
}

func (serverConfig) IdleTimeout() time.Duration {
	if v := os.Getenv("CONFIG_SERVER_IDLE_TIMEOUT"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 5 * time.Minute
}

func (serverConfig) MaxHeaderBytes() int64 {
	if v := os.Getenv("CONFIG_SERVER_MAX_HEADER_BYTES"); v != "" {
		if i, err := strconv.ParseInt(v, 10, 64); err == nil {
			return i
		}
	}
	return 1048576
}

func (serverConfig) ReadTimeout() time.Duration {
	if v := os.Getenv("CONFIG_SERVER_READ_TIMEOUT"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 15 * time.Second
}

func (serverConfig) ShutdownTimeout() time.Duration {
	if v := os.Getenv("CONFIG_SERVER_SHUTDOWN_TIMEOUT"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 2*time.Hour + 30*time.Minute
}

func (serverConfig) Timeout() time.Duration {
	if v := os.Getenv("CONFIG_SERVER_TIMEOUT"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 30 * time.Second
}

func (serverConfig) WriteTimeout() time.Duration {
	if v := os.Getenv("CONFIG_SERVER_WRITE_TIMEOUT"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return 15 * time.Second
}

func (serviceConfig) AllowedOrigins() []string {
	if v := os.Getenv("CONFIG_SERVICE_ALLOWED_ORIGINS"); v != "" {
		// Array overrides not supported via env vars
	}
	return []string{"https://example.com", "https://app.example.com"}
}

func (serviceConfig) Features() []string {
	if v := os.Getenv("CONFIG_SERVICE_FEATURES"); v != "" {
		// Array overrides not supported via env vars
	}
	return []string{"auth", "cache", "metrics"}
}

func (serviceConfig) Name() string {
	if v := os.Getenv("CONFIG_SERVICE_NAME"); v != "" {
		return v
	}
	return "api"
}

func (serviceConfig) Ports() []int64 {
	if v := os.Getenv("CONFIG_SERVICE_PORTS"); v != "" {
		// Array overrides not supported via env vars
	}
	return []int64{8080, 8081, 8082}
}

func (serviceConfig) Weights() []float64 {
	if v := os.Getenv("CONFIG_SERVICE_WEIGHTS"); v != "" {
		// Array overrides not supported via env vars
	}
	return []float64{1, 2.5, 3.7}
}

func Name() string {
	if v := os.Getenv("CONFIG_NAME"); v != "" {
		return v
	}
	return "cfgx"
}

var (
	App       appConfig
	Cache     cacheConfig
	Database  databaseConfig
	Endpoints []endpointsItem
	Features  []featuresItem
	Server    serverConfig
	Service   serviceConfig
)
